// Converts system-collected data into a prompt string for the AI model

export interface SystemFeedbackContext {
  // Triggered messages (from system-feedback.service.ts)
  triggeredMessages: Array<{
    type: string;
    message: string;
    suggestion: string;
  }>;

  // Student profile
  studentProfile: {
    completionRate7d: number;
    avgStress7d: number;
    consistencyScore: number;
  } | null;

  // Last week's overall workload self-assessment
  lastWeekloadFeedback: 'cok_yogundu' | 'tam_uygundu' | 'yetersizdi' | null;

  // Live context from the planner
  burnoutDetected: boolean;
  programZorlastu: boolean;
}

/**
 * Converts raw data into a prompt string for the AI model.
 *
 * The AI's job:
 * - Merge the triggered messages into a single, coherent message for the student.
 * - Stay silent when there are no messages (returns empty string; frontend hides it).
 * - Write in English, keep it short, motivating or cautionary — never judgmental.
 */
export function buildSystemFeedbackPrompt(context: SystemFeedbackContext): string {
  // No triggered messages — skip prompt generation
  if (context.triggeredMessages.length === 0) return '';

  const lines: string[] = [];

  // ── System findings ───────────────────────────────────────────────────────
  lines.push('The following observations were generated by a student study-tracking system for this week:');
  lines.push('');

  for (const msg of context.triggeredMessages) {
    lines.push(`- [${msg.type}] ${msg.message} → Suggestion: ${msg.suggestion}`);
  }

  lines.push('');

  // ── Student profile (if available) ───────────────────────────────────────
  if (context.studentProfile) {
    const p = context.studentProfile;
    lines.push('Student\'s general status over the last 7 days:');
    lines.push(`- Completion rate: ${Math.round(p.completionRate7d * 100)}% (share of planned blocks completed)`);
    lines.push(`- Average stress: ${p.avgStress7d.toFixed(1)} / 5`);
    lines.push(`- Study consistency: ${Math.round(p.consistencyScore * 100)}% (whether the student studies at least a little every day)`);
    lines.push('');
  }

  // ── Additional context ────────────────────────────────────────────────────
  const extraContext: string[] = [];

  if (context.burnoutDetected) {
    extraContext.push('This week\'s schedule was lightened (burnout signal detected).');
  }
  if (context.programZorlastu) {
    extraContext.push('Some difficult lessons had to be moved to heavier days.');
  }
  if (context.lastWeekloadFeedback === 'cok_yogundu') {
    extraContext.push('The student rated last week as too heavy.');
  } else if (context.lastWeekloadFeedback === 'yetersizdi') {
    extraContext.push('The student rated last week as insufficient.');
  }

  if (extraContext.length > 0) {
    lines.push('Additional context:');
    for (const ctx of extraContext) {
      lines.push(`- ${ctx}`);
    }
    lines.push('');
  }

  // ── Task definition ───────────────────────────────────────────────────────
  lines.push('Your task:');
  lines.push(
    'Turn the observations above into a single, fluent English message addressed to the student. ' +
    'Keep it short (2–3 sentences), write in a motivating or cautionary tone, ' +
    'and never be judgmental or critical. ' +
    'If multiple lessons appear in the observations, combine them into one message. ' +
    'The suggestions describe actions the student can take in the future — do not imply they have already been done. ' +
    'Do not suggest session lengths, scheduling, block placement, or timing — the planner handles all of that. ' +
    'Output only the message text — no headings, bullet points, or explanations.',
  );

  return lines.join('\n');
}